#- name: print ansible_lsb.id result
#  debug: var=ansible_lsb.id
  
- name: copy interfaces
  copy: src=scenario{{s}}/{{ansible_hostname}}/interfaces dest=/etc/network/
  
- name: copy Quagga daemons
  copy: src=scenario{{s}}/{{ansible_hostname}}/daemons dest=/etc/quagga/
  when: '"Cumulus" in ansible_lsb.id'
  
- name: copy Quagga conf
  copy: src=scenario{{s}}/{{ansible_hostname}}/Quagga.conf dest=/etc/quagga/
  when: '"Cumulus" in ansible_lsb.id'

- name: reload networking
  command: ifreload -a
  when: '"Cumulus" in ansible_lsb.id'

- name: reload quagga
  service: name=quagga state=restarted
  when: '"Cumulus" in ansible_lsb.id'

- name: Force Interfaces Down
  command: ifdown {{item}}
  with_items:
    - lo
    - lo:1
    - eth1
    - eth2
  when: '"Cumulus" not in ansible_lsb.id'
    
- name: Force Interfaces Up
  command: ifup {{item}}
  with_items:
    - lo
    - lo:1
    - eth1
    - eth2
  when: '"Cumulus" not in ansible_lsb.id'

- name: Check if mgmtvrf is installed
  shell: "dpkg-query -f '${binary:Package}\n' -W"
  register: mgmtvrf_installed
  notify: Install mgmtvrf
  when: '"Cumulus" in ansible_lsb.id'  
  
- name: Install mgmtvrf
  apt: name=cl-mgmtvrf update_cache=yes state=present cache_valid_time=86400
  when: "'cl-mgmtvrf' not in mgmtvrf_installed and 'Cumulus' in ansible_lsb.id" 
      
- name: Check if mgmtvrf is installed
  stat: path=/var/lib/cl-mgmtvrf/mgmtvrf.conf
  register: mgmtvrf
  when: '"Cumulus" in ansible_lsb.id'  

- name: Setup Mgmtvrf
  command: cl-mgmtvrf -e
  when: '"Cumulus" in ansible_lsb.id and mgmtvrf.stat.exists == False' 

- name: Check if default for eth1/eth2 is installed
  shell: "ip route show"
  register: default_installed
  notify: Add Default route if on server01
  when: "'server01' in ansible_hostname"
     
- name: Add Default route if on server01
  lineinfile: dest=/etc/rc.local line="ip route add default nexthop via 172.16.1.1 dev eth1 onlink nexthop via 172.16.1.1 dev eth2 onlink" insertbefore="exit 0"
  when: "'server01' in ansible_hostname and 'nexthop via 172.16.1.1' in default_installed"
 
- name: make sure default is present on server01
  command: ip route add default nexthop via 172.16.1.1 dev eth1 onlink nexthop via 172.16.1.1 dev eth2 onlink
  when: "'server01' in ansible_hostname and 'nexthop via 172.16.1.1' in default_installed"

- name: Check if default for eth1/eth2 is installed
  shell: "ip route show"
  register: default_installed
  notify: Add Default route if on server01
  when: "'server02' in ansible_hostname"
     
- name: Add Default route if on server01
  lineinfile: dest=/etc/rc.local line="ip route add default nexthop via 172.16.3.1 dev eth1 onlink nexthop via 172.16.3.1 dev eth2 onlink" insertbefore="exit 0"
  when: "'server02' in ansible_hostname and 'nexthop via 172.16.3.1' in default_installed"
 
- name: make sure default is present on server01
  command: ip route add default nexthop via 172.16.3.1 dev eth1 onlink nexthop via 172.16.3.1 dev eth2 onlink
  when: "'server02' in ansible_hostname and 'nexthop via 172.16.3.1' in default_installed"
