- name: copy interfaces
  copy: src=scenario{{s}}/{{ansible_hostname}}/interfaces dest=/etc/network/
  
- name: copy Quagga daemons
  copy: src=scenario{{s}}/{{ansible_hostname}}/daemons dest=/etc/quagga/
  when: '"Cumulus" in ansible_lsb'
  
- name: copy Quagga conf
  copy: src=scenario{{s}}/{{ansible_hostname}}/Quagga.conf dest=/etc/quagga/
  when: '"Cumulus" in ansible_lsb'

- name: reload networking
  command: ifreload -a
  when: '"Cumulus" in ansible_lsb'

- name: reload quagga
  service: name=quagga state=restarted
  when: '"Cumulus" in ansible_lsb'

- name: Force Interfaces Down
  command: ifup {{item}}
  with_items:
    - lo
    - lo:1
    - eth1
    - eth2
  when: '"Cumulus" not in ansible_lsb'
    
- name: Force Interfaces Up
  command: ifup {{item}}
  with_items:
    - lo
    - lo:1
    - eth1
    - eth2
  when: '"Cumulus" not in ansible_lsb'
    
